name: digestif

services:
  api:
    image: digestif
    env_file:
      - default.env
    build: .
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s
    volumes:
      - /root/images:/feeds
