name: digestif

services:
  digestif:
    image: digestif
    build: .
    pull_policy: build
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s
    volumes:
      - ${FEEDS_PATH:-./feeds}:/feeds
      - ${OUTPUT_PATH:-./outputs}:/outputs

